# Generated by Django 6.1 on 2026-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewround',
            name='round_type',
            field=models.CharField(choices=[('HR', 'HRRound'), ('Technical', 'TechnicalRound'), ('Final', 'FinalRound'), ('Managerial', 'ManagerialRound')], max_length=50),
        ),
    ]
